- win/posix/getopt.c
- win/posix/getopt.h
- win/sassc.sln
- win/sassc.vcxproj
Corresponds to sass/libsass#810.
> Build: Adds solution files for VS

- Makefile
- Makefile.am
Related to https://github.com/sass/libsass/pull/919
Just a minor build improvement.
Plus some white-space cleaned.
> Build support for plugin loader (add ld lib when linking)

- Readme.md
Fixed sass-spec GitHub link in the readme.
> Fix sass-spec link

- Readme.md
With respect to my recent misunderstanding in how to use sassC here is PR with step-by-step instructions that would have saved me some time.
My main misunderstanding was that I thought you had to have libsass actually installed (as opposed to just having the cloned the repo).
> adding simple step-by-step install guide

- Makefile
More shell invocations going wrong!
> Hotfix for mingw64 build issues

- Makefile
- Makefile.am
- configure.ac
- script/ci-build-libsass
Needed to pass CI after https://github.com/sass/libsass/pull/1352
> Update Makefiles to reflect source re-organization

- Makefile
Some more fixes taken from libsass makefile improvements!
> Further makefile improvements

- .gitignore
- win/sassc.sln
* Also adds `.user` (VS user file) to `.gitignore`.
> win: Fixes Release mode in VS .sln file

- .travis.yml
- script/ci-build-libsass
Update for new travis container based build infrastructure.
> Use Travis-CI container-based infrastructure

- sassc.c
https://github.com/sass/libsass/pull/1538
> Update for the new 3.3 header layout

- Makefile
This was left over and can IMO be removed completely
> Remove obsolete comments in Makefile

- sassc.c
Fixes https://github.com/sass/sassc/issues/147
> Support -p as advertised

- Makefile
Need this to make installer build automatization work
-> https://github.com/mgreter/libsass-msi-installer
> Improve makefile compatibility (mingw in dos cmd)

- sassc.c
This should fix issues with hanging CI when assertions are triggered!
> Ensure assertions are printed on stderr

- sassc.c
This is a PR to use sass_option_push_include_path as fixed in [libsass#1974](https://github.com/sass/libsass/pull/1974)
> Use sass_option_push_include_path

- sassc.c
Depends on https://github.com/sass/libsass/pull/2021
> Print out the sass version too.

- docs/building/unix-instructions.md
- script/bootstrap
Test to see if the dev has set up the environmental variables for these repos, and clone them out of the source tree if they haven't.
> Add  script/bootstrap for setting up libsass and sass-spec dependecies

- sassc.c
https://llvm.org/bugs/show_bug.cgi?id=11536
> Avoid clang warning (-Warray-bounds)

- LICENSE
- Readme.md
@hcatlin for your approval. 
I just took the text you changed for libsass in https://github.com/sass/libsass/pull/1906
> Update contributing license agreement to match libsass

- win/sassc.vcxproj
- win/sassc.vcxproj.filters
Improve settings for release build! Was compiled with _DEBUG (ie slow. `malloc_dbg`)!
> Update windows MSVC build files

- sassc.c
Fixes https://github.com/sass/libsass/issues/2162
Related to https://github.com/sass/sass/pull/2182
> Use more specific error exit codes (posix/win)

- sassc.c
> Fix CLI sourcemap argument

- sassc.c
This reverts commit 548744e1d8a68c003c86d0e47ee3078a6a327473.
See https://github.com/sass/libsass/pull/2684
> Revert "Add --import-extensions flag"

- win/sassc.vcxproj.filters
See https://github.com/sass/libsass/pull/2793
> Remove reference to src/functions.hpp

- sassc.c
> added support for SASS_PATH env variable

- docs/building/windows-instructions.md
Beginners, those unfamiliar with Visual Studio, and those unfamiliar with building executables in general may get hung up on "do the finger dance" parlance.
> add alternative to "do the finger dance" method

- Readme.md
> Add a deprecation message to the readme
