sass/sassc

- sassc.c
- sassloop.c
This PR is the corresponding sassc removal of `image-path` for https://github.com/sass/libsass/pull/834.
/cc @mgreter
> Remove the image-path option

- Makefile.am
- configure.ac
- version.sh
This is closely related to https://github.com/sass/libsass/pull/906
Moves version fetch code into external shell script.
Adds another possibility to provide the version on compile
time by VERSION file. We still give higher priority to the
environment variable or the version from git if available.
> Remove hard-coded version from autotools build

- sassc.c
Related to https://github.com/sass/libsass/pull/910 and https://github.com/sass/sass-spec/pull/270
- Enable missing output style options
> Implement all output styles

- Makefile
Needed for plugin loading to compile.
It will still link libsass statically bot not system libs!
Not sure if anyone really uses it, otherwise we would probably need another flag to disable the complete plugin part in libsass. Although it doesn't seem to work on mac anyway, so IMO not a big change!
It now actually links exactly as the automake build!
> Remove static linker flag from build

- .gitignore
- sassc.c
`sass_clear_context()` is calling
now `free()` on `source_string`
> Double free() fault

- sassc.c
Without this extra line a missing command will cause sassc to crash:
```
./bin/sassc --something-missing
```
> Add termination line to arg list to prevent crash

- Makefile
Shell invocation seems to go wrong!
Reverts one feature previousely merged!
> Hotfix for mingw64 build issues

- .travis.yml
- sassc.c
- win/posix/getopt.c
I'm busy creating a bundled solution out of libsass, sassc, and libsass-net: https://github.com/CapitalID/Sass-Win-Bundle. 
Unfortunatly sassc didn't build. 
The changes proposed in this PR fix these build errors & warnings.
> Fix sassc build and warnings

- .gitignore
- win/sassc.vcxproj
- win/sassc.vcxproj.filters
* This enables LibSass CI to use `libsass\sassc\win\sassc.sln`, which
produces `sassc.exe`, while `libsass\win\libsass.sln` will produce
`libsass.dll` (or static `libsass.lib`, if sets environment variable:
`LIBSASS_STATIC_LIB` to `1`). Related PR: sass/libsass#1439.
* Shares the same source tree as `libsass.vcxproj` using common
`libsass.targets`.
* Backward compatible for VS2013.
> Build: Upgrades VS files to support VS2015

- Readme.md
- docs/building/unix-instructions.md
- docs/building/windows-instructions.md
- docs/testing/unix-instructions.md
- docs/testing/windows-instructions.md
* Creates `docs/[build/test]ing` directories at the root.
* Purges build and test related instruction from README into:
`[build/test]ing/unix-instructions`.
* Adds corresponding Windows instructions.
* Adds links in README to markdown files under docs directory.
> Docs: Adds Unix and Windows instructions

- Makefile
- Makefile.am
- configure.ac
Problem:
```
configure:15694: checking for libsass_version in -lsass
configure:15719: g++ -o conftest -g -O2  -I/home/travis/build/mgreter/sassc/include  -L/home/travis/build/mgreter/sassc/lib conftest.cpp -lsass   >&5
/home/travis/build/mgreter/sassc/lib/libsass.a(plugins.o): In function `Sass::Plugins::load_plugin(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/travis/build/mgreter/sassc/libsass/src/plugins.cpp:49: undefined reference to `dlopen'
/home/travis/build/mgreter/sassc/libsass/src/plugins.cpp:52: undefined reference to `dlsym'
/home/travis/build/mgreter/sassc/libsass/src/plugins.cpp:57: undefined reference to `dlsym'
/home/travis/build/mgreter/sassc/libsass/src/plugins.cpp:63: undefined reference to `dlsym' …
```
> Fix travis ci static automake lib

- .gitignore
- bin/.gitignore
After build, `git status` was showing files and folders under `bin/`. This PR removes the obsolete `win/bin` rule from .gitignore and renames `bin/.gitkeep` to `bin/.gitignore` with omission rule for all files except for itself.
> Repo: Moves .gitkeep to .gitignore

- docs/building/windows-instructions.md
- sassc.c
While testing sass/libsass#1774, I found another issue with UTF8 and sassc on Windows: the `char** argv` disregards the Unicode/multibyte characters passed through stdin. Note that sass/libsass#1774 is not dependent on this by the reciprocal is true.
Also added a missing `&` in windows build steps doc.
> win: Converts ANSI argv to UTF8 array

- docs/building/windows-instructions.md
- win/sassc.vcxproj
At present, `sass -v` is returning empty string for libsass and sassc
versions.
Seems like we missed one attribute: `ConsoleToMSBuild="true"`.
> win: Emits version to VS property

- sassc.c
With MSVC printing "\n" on stdout results in "\r\n" by
default. This means that if we already have "\r\n", the
final string we end up on outputting is "\r\r\n".
> Change output to binary mode

- win/sassc.vcxproj
- win/sassc.vcxproj.filters
Accompanying https://github.com/sass/libsass/pull/2060 - Changes MSVC to put object files into subdirectories.
> Split AST source into multiple compile units

- configure.ac
This should address https://github.com/sass/sassc/pull/172 and work with mingw64 too.
Also adds another fix from https://github.com/sass/libsass/pull/2063
> Fix automake compile on msys2 and mingw64

- sassc.c
This pull just checks if `argc == 1` and if so, prints the usage guide and returns 0 just like calling it with `-h` would.
> sassc hangs when called with no args

- sassc.c
Will check if STDIN is associated with an interactive fd using `isatty()`, from either `io.h` when on Windows or `unistd.h` when on POSIX. If no data is being piped through STDIN, and no arguments were passed, will print usage and `return 0;` just like calling it with `-h` would.
> Fixed hang when called with no args or STDIN piped data

- .editorconfig
- .gitignore
- win/sassc.vcxproj
- win/sassc.vcxproj.filters
- Add missing LIBSASS_INCLUDES_DIR reference
- Fix AdditionalIncludeDirectories so base.h and the other include\sass
files are found
- Update filter paths from latest libsass.targets
> Windows: Add editorconfig and fix filterpaths for latest libsass

- sassc.c
Needs https://github.com/sass/libsass/pull/2213
Allocated on line 230 by `sass_make_options`
> Fix memory leak by freeing options we allocated

- Makefile
Flag -ldl is removed only for FreeBSD
Support OpenBSD too
> Remove -ldl flag for OpenBSD

- sassc.c
> Use context object to get map file path

- docs/building/unix-instructions.md
- docs/building/windows-instructions.md
- win/sassc.sln
- win/sassc.vcxproj
Add more configurations to static compile VCR libs.
Also:
* simplified the whole configuration matrix logic in `sassc.vcxproj` (bitness x configuration)
* updated the docs accordingly
* added `.SolutionItems` in `sassc.sln` and linked several repo files (`.gitignore`, `README.md` etc.) and docs directory.
Fix #199
> Ability to static compile VCR libs

- win/sassc.vcxproj
- win/sassc.vcxproj.filters
It's only one MB by default, which we have seen to be too little for some more advanced use cases.
> Increase stack size for MSVC to 4MB

- sassc.c
Fixes https://github.com/sass/sassc/issues/213
Fixes https://github.com/sass/sassc/issues/210
> Implement inline and auto sourcemap options

- sassc.c
This will enable consumers to continue using raw css imports when
it's remove from LibSass.
Depends on https://github.com/sass/libsass/pull/2615
> Add --import-extensions flag

- sassc.c
> Two colons mean an option takes an optional arg; if there
> is text in the current argv-element (i.e., in the same word
> as the option name itself, for example, "-oarg"), then it
> is returned in optarg, otherwise optarg is set to zero.
> Fix optional short source-map argument

- sassc.c
The typo was caught by the Debian Lintian tool:
```
I: sassc: spelling-error-in-binary usr/bin/sassc occured occurred
N: 
N:    Lintian found a spelling error in the given binary. Lintian has a list
N:    of common misspellings that it looks for. It does not have a dictionary
N:    like a spelling checker does.
```
Many thanks!
> Fix a minor typo in sassc.c

- Makefile
1. Use `cc` and `c++` compilers for compatibility with systems where gcc is not installed or is not the default compiler.
2. Use the `c++11` standard instead of `{gnu,c}++0x`.
3. Flatten nested ifs in UNAME/TARGET detection.
> Port over some Makefile changes from libsass

- CODE_OF_CONDUCT.md
- Readme.md
See https://github.com/sass/sass-site/issues/217
Committed via https://github.com/asottile/all-repos
> https-ify sass-lang.com urls

- .gitignore
This file is used to hardcode the version for releases
that are not able to query the version from git directly.
Once generated it can mess up the state for a submodule.
> Add VERSION file to gitignore

- Makefile
- sassc.c
- Use dylib instead of so on Mac OSX
- Remove unnessecary MSVC project file
- Suppress MSVC assert popups
With this LibSass build needs some fixups.
See https://stackoverflow.com/questions/35568122/why-isnt-dyld-library-path-being-propagated-here
> Improve Mac OSX shared native makefile build

- docs/building/unix-instructions.md
enabled-shared is only an option for the lib, not sassc
> remove enabled-shared from sassc instructions
